platform :ios, '9.0'
target :'LandOfVoca' do
  use_frameworks!

    # Analytics dependency
    pod 'AWSPinpoint', '~> 2.6.5'

    # other pods
    pod 'SwiftyJSON'
    pod 'Alamofire'
    #UI pods
    
end
